import os
import requests

def download_noto_fonts(destination_dir="C:/Fonts/Noto"):
    os.makedirs(destination_dir, exist_ok=True)

    LANGUAGE_FONT_MAP = {
        'en': 'NotoSans-Regular.ttf',
        'aa': 'NotoSans-Regular.ttf',
        'ab': 'NotoSans-Regular.ttf',
        'ae': 'NotoSans-Regular.ttf',
        'af': 'NotoSans-Regular.ttf',
        'ak': 'NotoSans-Regular.ttf',
        'am': 'NotoSansEthiopic-Regular.ttf',
        'an': 'NotoSans-Regular.ttf',
        'ar': 'NotoNaskhArabic-Regular.ttf',
        'as': 'NotoSansBengali-Regular.ttf',
        'av': 'NotoSans-Regular.ttf',
        'ay': 'NotoSans-Regular.ttf',
        'az': 'NotoSans-Regular.ttf',
        'ba': 'NotoSans-Regular.ttf',
        'be': 'NotoSans-Regular.ttf',
        'bg': 'NotoSans-Regular.ttf',
        'bh': 'NotoSansDevanagari-Regular.ttf',
        'bi': 'NotoSans-Regular.ttf',
        'bm': 'NotoSans-Regular.ttf',
        'bn': 'NotoSansBengali-Regular.ttf',
        'bo': 'NotoSansTibetan-Regular.ttf',
        'br': 'NotoSans-Regular.ttf',
        'bs': 'NotoSans-Regular.ttf',
        'ca': 'NotoSans-Regular.ttf',
        'ce': 'NotoSans-Regular.ttf',
        'ch': 'NotoSans-Regular.ttf',
        'co': 'NotoSans-Regular.ttf',
        'cr': 'NotoSansCanadianAboriginal-Regular.ttf',
        'cs': 'NotoSans-Regular.ttf',
        'cu': 'NotoSans-Regular.ttf',
        'cv': 'NotoSans-Regular.ttf',
        'cy': 'NotoSans-Regular.ttf',
        'da': 'NotoSans-Regular.ttf',
        'de': 'NotoSans-Regular.ttf',
        'dv': 'NotoSansThaana-Regular.ttf',
        'dz': 'NotoSansTibetan-Regular.ttf',
        'ee': 'NotoSans-Regular.ttf',
        'el': 'NotoSansGreek-Regular.ttf',
        'eo': 'NotoSans-Regular.ttf',
        'es': 'NotoSans-Regular.ttf',
        'et': 'NotoSans-Regular.ttf',
        'eu': 'NotoSans-Regular.ttf',
        'fa': 'NotoNaskhArabic-Regular.ttf',
        'ff': 'NotoSans-Regular.ttf',
        'fi': 'NotoSans-Regular.ttf',
        'fj': 'NotoSans-Regular.ttf',
        'fo': 'NotoSans-Regular.ttf',
        'fr': 'NotoSans-Regular.ttf',
        'fy': 'NotoSans-Regular.ttf',
        'ga': 'NotoSans-Regular.ttf',
        'gd': 'NotoSans-Regular.ttf',
        'gl': 'NotoSans-Regular.ttf',
        'gn': 'NotoSans-Regular.ttf',
        'gu': 'NotoSansGujarati-Regular.ttf',
        'gv': 'NotoSans-Regular.ttf',
        'ha': 'NotoSans-Regular.ttf',
        'he': 'NotoSansHebrew-Regular.ttf',
        'hi': 'NotoSansDevanagari-Regular.ttf',
        'ho': 'NotoSans-Regular.ttf',
        'hr': 'NotoSans-Regular.ttf',
        'ht': 'NotoSans-Regular.ttf',
        'hu': 'NotoSans-Regular.ttf',
        'hy': 'NotoSansArmenian-Regular.ttf',
        'hz': 'NotoSans-Regular.ttf',
        'ia': 'NotoSans-Regular.ttf',
        'id': 'NotoSans-Regular.ttf',
        'ie': 'NotoSans-Regular.ttf',
        'ig': 'NotoSans-Regular.ttf',
        'ii': 'NotoSansYi-Regular.ttf',
        'ik': 'NotoSans-Regular.ttf',
        'io': 'NotoSans-Regular.ttf',
        'is': 'NotoSans-Regular.ttf',
        'it': 'NotoSans-Regular.ttf',
        'iu': 'NotoSansCanadianAboriginal-Regular.ttf',
        'ja': 'NotoSansJP-Regular.otf',
        'jv': 'NotoSans-Regular.ttf',
        'ka': 'NotoSansGeorgian-Regular.ttf',
        'kg': 'NotoSans-Regular.ttf',
        'ki': 'NotoSans-Regular.ttf',
        'kj': 'NotoSans-Regular.ttf',
        'kk': 'NotoSans-Regular.ttf',
        'kl': 'NotoSans-Regular.ttf',
        'km': 'NotoSansKhmer-Regular.ttf',
        'kn': 'NotoSansKannada-Regular.ttf',
        'ko': 'NotoSansKR-Regular.otf',
        'kr': 'NotoSans-Regular.ttf',
        'ks': 'NotoSans-Regular.ttf',
        'ku': 'NotoSans-Regular.ttf',
        'kv': 'NotoSans-Regular.ttf',
        'kw': 'NotoSans-Regular.ttf',
        'ky': 'NotoSans-Regular.ttf',
        'la': 'NotoSans-Regular.ttf',
        'lb': 'NotoSans-Regular.ttf',
        'lg': 'NotoSans-Regular.ttf',
        'li': 'NotoSans-Regular.ttf',
        'ln': 'NotoSans-Regular.ttf',
        'lo': 'NotoSansLao-Regular.ttf',
        'lt': 'NotoSans-Regular.ttf',
        'lu': 'NotoSans-Regular.ttf',
        'lv': 'NotoSans-Regular.ttf',
        'mg': 'NotoSans-Regular.ttf',
        'mh': 'NotoSans-Regular.ttf',
        'mi': 'NotoSans-Regular.ttf',
        'mk': 'NotoSans-Regular.ttf',
        'ml': 'NotoSansMalayalam-Regular.ttf',
        'mn': 'NotoSansMongolian-Regular.ttf',
        'mr': 'NotoSansDevanagari-Regular.ttf',
        'ms': 'NotoSans-Regular.ttf',
        'mt': 'NotoSans-Regular.ttf',
        'my': 'NotoSansMyanmar-Regular.ttf',
        'na': 'NotoSans-Regular.ttf',
        'nb': 'NotoSans-Regular.ttf',
        'nd': 'NotoSans-Regular.ttf',
        'ne': 'NotoSansDevanagari-Regular.ttf',
        'ng': 'NotoSans-Regular.ttf',
        'nl': 'NotoSans-Regular.ttf',
        'nn': 'NotoSans-Regular.ttf',
        'no': 'NotoSans-Regular.ttf',
        'nr': 'NotoSans-Regular.ttf',
        'nv': 'NotoSans-Regular.ttf',
        'ny': 'NotoSans-Regular.ttf',
        'oc': 'NotoSans-Regular.ttf',
        'oj': 'NotoSansCanadianAboriginal-Regular.ttf',
        'om': 'NotoSans-Regular.ttf',
        'or': 'NotoSansOriya-Regular.ttf',
        'os': 'NotoSans-Regular.ttf',
        'pa': 'NotoSansGurmukhi-Regular.ttf',
        'pi': 'NotoSansDevanagari-Regular.ttf',
        'pl': 'NotoSans-Regular.ttf',
        'ps': 'NotoNaskhArabic-Regular.ttf',
        'pt': 'NotoSans-Regular.ttf',
        'qu': 'NotoSans-Regular.ttf',
        'rm': 'NotoSans-Regular.ttf',
        'rn': 'NotoSans-Regular.ttf',
        'ro': 'NotoSans-Regular.ttf',
        'ru': 'NotoSans-Regular.ttf',
        'rw': 'NotoSans-Regular.ttf',
        'sa': 'NotoSansDevanagari-Regular.ttf',
        'sc': 'NotoSans-Regular.ttf',
        'sd': 'NotoSansDevanagari-Regular.ttf',
        'se': 'NotoSans-Regular.ttf',
        'sg': 'NotoSans-Regular.ttf',
        'si': 'NotoSansSinhala-Regular.ttf',
        'sk': 'NotoSans-Regular.ttf',
        'sl': 'NotoSans-Regular.ttf',
        'sm': 'NotoSans-Regular.ttf',
        'sn': 'NotoSans-Regular.ttf',
        'so': 'NotoSans-Regular.ttf',
        'sq': 'NotoSans-Regular.ttf',
        'sr': 'NotoSans-Regular.ttf',
        'ss': 'NotoSans-Regular.ttf',
        'st': 'NotoSans-Regular.ttf',
        'su': 'NotoSans-Regular.ttf',
        'sv': 'NotoSans-Regular.ttf',
        'sw': 'NotoSans-Regular.ttf',
        'ta': 'NotoSansTamil-Regular.ttf',
        'te': 'NotoSansTelugu-Regular.ttf',
        'tg': 'NotoSans-Regular.ttf',
        'th': 'NotoSansThai-Regular.ttf',
        'ti': 'NotoSansEthiopic-Regular.ttf',
        'tk': 'NotoSans-Regular.ttf',
        'tl': 'NotoSans-Regular.ttf',
        'tn': 'NotoSans-Regular.ttf',
        'to': 'NotoSans-Regular.ttf',
        'tr': 'NotoSans-Regular.ttf',
        'ts': 'NotoSans-Regular.ttf',
        'tt': 'NotoSans-Regular.ttf',
        'tw': 'NotoSans-Regular.ttf',
        'ty': 'NotoSans-Regular.ttf',
        'ug': 'NotoSansArabic-Regular.ttf',
        'uk': 'NotoSans-Regular.ttf',
        'ur': 'NotoNastaliqUrdu-Regular.ttf',
        'uz': 'NotoSans-Regular.ttf',
        've': 'NotoSans-Regular.ttf',
        'vi': 'NotoSans-Regular.ttf',
        'vo': 'NotoSans-Regular.ttf',
        'wa': 'NotoSans-Regular.ttf',
        'wo': 'NotoSans-Regular.ttf',
        'xh': 'NotoSans-Regular.ttf',
        'yi': 'NotoSansHebrew-Regular.ttf',
        'yo': 'NotoSans-Regular.ttf',
        'za': 'NotoSans-Regular.ttf',
        'zh': 'NotoSansSC-Regular.otf',
        'zu': 'NotoSans-Regular.ttf'
    }

    fallback_urls = [
        "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf",
        "https://github.com/googlefonts/noto-fonts/raw/main/hinted/otf",
        "https://github.com/googlefonts/noto-cjk/raw/main/Sans/OTF"
    ]

    for lang, font_file in LANGUAGE_FONT_MAP.items():
        save_path = os.path.join(destination_dir, font_file)
        if os.path.exists(save_path):
            print(f"[SKIP] Already exists: {font_file}")
            continue

        success = False
        for base_url in fallback_urls:
            url = f"{base_url}/{font_file}"
            try:
                response = requests.get(url, timeout=10)
                if response.status_code == 200:
                    with open(save_path, "wb") as f:
                        f.write(response.content)
                    print(f"[OK] Downloaded: {font_file}")
                    success = True
                    break
            except Exception as e:
                continue

        if not success:
            print(f"[FAIL] Could not download: {font_file}")

if __name__ == "__main__":
    download_noto_fonts()
