LANGUAGE_FONT_MAP = {
    'en': 'NotoSans-Regular.ttf',                   # English

    'af': 'NotoSans-Regular.ttf',                   # Afrikaans
    'sq': 'NotoSans-Regular.ttf',                   # Albanian
    'am': 'NotoSansEthiopic-Regular.ttf',           # Amharic
    'ar': 'NotoNaskhArabic-Regular.ttf',            # Arabic
    'hy': 'NotoSansArmenian-Regular.ttf',           # Armenian
    'as': 'NotoSansBengali-Regular.ttf',            # Assamese
    'az': 'NotoSans-Regular.ttf',                   # Azerbaijani
    'eu': 'NotoSans-Regular.ttf',                   # Basque
    'be': 'NotoSans-Regular.ttf',                   # Belarusian
    'bn': 'NotoSansBengali-Regular.ttf',            # Bengali
    'bs': 'NotoSans-Regular.ttf',                   # Bosnian
    'bg': 'NotoSans-Regular.ttf',                   # Bulgarian
    'my': 'NotoSansMyanmar-Regular.ttf',            # Burmese
    'ca': 'NotoSans-Regular.ttf',                   # Catalan
    'zh': 'NotoSansSC-Regular.otf',                 # Chinese
    'hr': 'NotoSans-Regular.ttf',                   # Croatian
    'cs': 'NotoSans-Regular.ttf',                   # Czech
    'da': 'NotoSans-Regular.ttf',                   # Danish
    'dv': 'NotoSansThaana-Regular.ttf',             # Divehi
    'nl': 'NotoSans-Regular.ttf',                   # Dutch
    'eo': 'NotoSans-Regular.ttf',                   # Esperanto
    'et': 'NotoSans-Regular.ttf',                   # Estonian
    'fi': 'NotoSans-Regular.ttf',                   # Finnish
    'fr': 'NotoSans-Regular.ttf',                   # French
    'gl': 'NotoSans-Regular.ttf',                   # Galician
    'ka': 'NotoSansGeorgian-Regular.ttf',           # Georgian
    'de': 'NotoSans-Regular.ttf',                   # German
    'el': 'NotoSansGreek-Regular.ttf',              # Greek
    'gu': 'NotoSansGujarati-Regular.ttf',           # Gujarati
    'ht': 'NotoSans-Regular.ttf',                   # Haitian
    'ha': 'NotoSans-Regular.ttf',                   # Hausa
    'he': 'NotoSansHebrew-Regular.ttf',             # Hebrew
    'hi': 'NotoSansDevanagari-Regular.ttf',         # Hindi
    'hu': 'NotoSans-Regular.ttf',                   # Hungarian
    'is': 'NotoSans-Regular.ttf',                   # Icelandic
    'ig': 'NotoSans-Regular.ttf',                   # Igbo
    'id': 'NotoSans-Regular.ttf',                   # Indonesian
    'iu': 'NotoSansCanadianAboriginal-Regular.ttf', # Inuktitut
    'ga': 'NotoSans-Regular.ttf',                   # Irish
    'it': 'NotoSans-Regular.ttf',                   # Italian
    'ja': 'NotoSansJP-Regular.otf',                 # Japanese
    'kn': 'NotoSansKannada-Regular.ttf',            # Kannada
    'ks': 'NotoSansDevanagari-Regular.ttf',         # Kashmiri
    'kk': 'NotoSans-Regular.ttf',                   # Kazakh
    'km': 'NotoSansKhmer-Regular.ttf',              # Khmer
    'rw': 'NotoSans-Regular.ttf',                   # Kinyarwanda
    'ko': 'NotoSansKR-Regular.otf',                 # Korean
    'ku': 'NotoNaskhArabic-Regular.ttf',            # Kurdish
    'lo': 'NotoSansLao-Regular.ttf',                # Lao
    'la': 'NotoSans-Regular.ttf',                   # Latin
    'lv': 'NotoSans-Regular.ttf',                   # Latvian
    'ln': 'NotoSans-Regular.ttf',                   # Lingala
    'lt': 'NotoSans-Regular.ttf',                   # Lithuanian
    'mk': 'NotoSans-Regular.ttf',                   # Macedonian
    'mg': 'NotoSans-Regular.ttf',                   # Malagasy
    'ms': 'NotoSans-Regular.ttf',                   # Malay
    'ml': 'NotoSansMalayalam-Regular.ttf',          # Malayalam
    'mt': 'NotoSans-Regular.ttf',                   # Maltese
    'mi': 'NotoSans-Regular.ttf',                   # Maori
    'mr': 'NotoSansDevanagari-Regular.ttf',         # Marathi
    'mn': 'NotoSansMongolian-Regular.ttf',          # Mongolian
    'se': 'NotoSans-Regular.ttf',                   # Northern Sami
    'no': 'NotoSans-Regular.ttf',                   # Norwegian
    'nb': 'NotoSans-Regular.ttf',                   # Norwegian Bokmål
    'or': 'NotoSansOriya-Regular.ttf',              # Oriya
    'ps': 'NotoNaskhArabic-Regular.ttf',            # Pashto
    'fa': 'NotoNaskhArabic-Regular.ttf',            # Persian
    'pl': 'NotoSans-Regular.ttf',                   # Polish
    'pt': 'NotoSans-Regular.ttf',                   # Portuguese
    'pa': 'NotoSansGurmukhi-Regular.ttf',           # Punjabi
    'ro': 'NotoSans-Regular.ttf',                   # Romanian
    'ru': 'NotoSans-Regular.ttf',                   # Russian
    'sm': 'NotoSans-Regular.ttf',                   # Samoan
    'sr': 'NotoSans-Regular.ttf',                   # Serbian
    'sn': 'NotoSans-Regular.ttf',                   # Shona
    'sd': 'NotoSansDevanagari-Regular.ttf',         # Sindhi
    'si': 'NotoSansSinhala-Regular.ttf',            # Sinhala
    'sk': 'NotoSans-Regular.ttf',                   # Slovak
    'sl': 'NotoSans-Regular.ttf',                   # Slovenian
    'so': 'NotoSans-Regular.ttf',                   # Somali
    'st': 'NotoSans-Regular.ttf',                   # Southern Sotho
    'es': 'NotoSans-Regular.ttf',                   # Spanish
    'sw': 'NotoSans-Regular.ttf',                   # Swahili
    'sv': 'NotoSans-Regular.ttf',                   # Swedish
    'tl': 'NotoSans-Regular.ttf',                   # Tagalog
    'ty': 'NotoSans-Regular.ttf',                   # Tahitian
    'tg': 'NotoSans-Regular.ttf',                   # Tajik
    'ta': 'NotoSansTamil-Regular.ttf',              # Tamil
    'tt': 'NotoSans-Regular.ttf',                   # Tatar
    'te': 'NotoSansTelugu-Regular.ttf',             # Telugu
    'th': 'NotoSansThai-Regular.ttf',               # Thai
    'bo': 'NotoSerifTibetan-Regular.ttf',           # Tibetan
    'ti': 'NotoSansEthiopic-Regular.ttf',           # Tigrinya
    'to': 'NotoSans-Regular.ttf',                   # Tonga
    'tn': 'NotoSans-Regular.ttf',                   # Tswana
    'tr': 'NotoSans-Regular.ttf',                   # Turkish
    'tk': 'NotoSans-Regular.ttf',                   # Turkmen
    'ug': 'NotoSans-Regular.ttf',                   # Uyghur
    'uk': 'NotoSans-Regular.ttf',                   # Ukrainian
    'ur': 'NotoNaskhArabic-Regular.ttf',            # Urdu
    'uz': 'NotoSans-Regular.ttf',                   # Uzbek
    'vi': 'NotoSans-Regular.ttf',                   # Vietnamese
    'cy': 'NotoSans-Regular.ttf',                   # Welsh
    'xh': 'NotoSans-Regular.ttf',                   # Xhosa
    'yi': 'NotoSansHebrew-Regular.ttf',             # Yiddish
    'yo': 'NotoSans-Regular.ttf',                   # Yoruba
    'zu': 'NotoSans-Regular.ttf'                    # Zulu
}